[DRAFT] Fix typos/errors
J-SNACKKB/autoeval pull request #6
Opened 2022-10-03 11:00 UTC by joaquimgomez

Once applied this PR will fix typos and errors:

- [ ] In README, for SCL: `residues_to_value` -> `residues_to_class`

2023-07-06 19:46 UTC, SebieF requested changes
Nice :) Besides the minor issues, I am wondering if autoeval is able to identify the correct fasta file from FLIP directly if only the split is provided as an argument? If this is not the case I would suggest to add this functionality for convenience, but maybe I am also just missing something..

Another nice thing to do would be to update the poetry.lock file via `poetry update` or `poetry lock`. `setuptools = "58.5.1"` can also be removed from the .toml file because it has been updated in biotrainer.

2023-07-06 19:46 UTC, SebieF commented on Dockerfile
> +#docker pull ghcr.io/sacdallago/biotrainer:latest
This line can be removed

2023-07-06 19:46 UTC, SebieF commented on README.md
>  - ✅: Available in configsbank in the closest possible way to the better configuration in the reference.
```suggestion
- ✅: Available in configsbank is the closest possible way to the best configuration in the reference.
```

2023-07-06 19:46 UTC, SebieF commented on autoeval/managers/data.py
> +        if (min_size is not None and len(entry.seq) > min_size) 222 (max_size is not None and len(entry.seq) < max_size):
```suggestion
        if (min_size is not None and len(entry.seq) > min_size) or (max_size is not None and len(entry.seq) < max_size):
```

2023-07-08 11:26 UTC, joaquimgomez commented on autoeval/managers/data.py
> +        if (min_size is not None and len(entry.seq) > min_size) 222 (max_size is not None and len(entry.seq) < max_size):
I don't know when this happened, but I know I solved it, and I also don't know how this ends here in the repo. Git mysteries.

2023-07-08 22:39 UTC, joaquimgomez commented
Thanks @SebieF  for reviewing the PR.

Regarding using AutoEval only with the split name as input argument, the answer is no, it's not possible.
Because, the point of using also as input the protocol and the working directory is that the user can decide to change which protocol they want to use, something feasible for some tasks like SCL (could work with residues/residue_to_class).

But I agree that this could also be simplified/improved by:
- If no working directory is given, then use `./output`
- If no protocol is given, then use the default one defined in `utilities/settings.py.`

If you agree, I implement the idea.

I updated poetry.

2023-07-15 17:18 UTC, SebieF commented
Ah sure, making the protocol a required option is fine! Adding the default working directory would be neat :)

I added some typo, format and type fixes to data.py and FASTA.py that I occurred during the review, shouldn't have changed anything about the logic

2024-03-01 10:28 UTC, merged